spring:
  application:
    name: 论坛系统
  output:
    ansi:
      enabled: always
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/forum_db?characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 2066

logging:
  pattern:
    dateformat: MM-dd HH:mm:ss
  level:
    root: info
    com.antoine.forum: debug
  file:
    path: E:/log/forum

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
